// @ts-nocheck
import { mutation } from "./_generated/server";

export default mutation({
  handler: async (ctx) => {
    // Clear existing products
    const existing = await ctx.db.query("ec_products").collect();
    for (const p of existing) { await ctx.db.delete(p._id); }

    const products = [
      {
        name: "Apex Tech Joggers",
        slug: "apex-tech-joggers",
        description: "Engineered with moisture-wicking 4-way stretch fabric. Deep side pockets, tapered fit, reflective logo detail. Perfect for training or streetwear.",
        price: 88.00,
        comparePrice: 110.00,
        category: "bottoms",
        gender: "men",
        images: [
          "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800",
          "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&q=80&w=800",
        ],
        colors: ["#111111", "#555555", "#cccccc"],
        sizes: ["XS", "S", "M", "L", "XL"],
        stock: 42,
        rating: 4.7,
        reviewCount: 128,
        featured: true,
        isNew: false,
        tags: ["training", "joggers", "bestseller"],
      },
      {
        name: "Velocity Performance Tee",
        slug: "velocity-performance-tee",
        description: "Ultra-lightweight performance fabric with anti-odor technology. Seamless construction eliminates chafing. Stays dry through any workout.",
        price: 45.00,
        category: "tops",
        gender: "unisex",
        images: [
          "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=800",
          "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&q=80&w=800",
        ],
        colors: ["#ffffff", "#111111", "#1e40af"],
        sizes: ["XS", "S", "M", "L", "XL", "XXL"],
        stock: 85,
        rating: 4.5,
        reviewCount: 96,
        featured: true,
        isNew: false,
        tags: ["performance", "tee", "training"],
      },
      {
        name: "Aero Windbreaker",
        slug: "aero-windbreaker",
        description: "Packable windbreaker with water-resistant finish. Lightweight enough to store in your pocket. Adjustable hood and cuffs for custom fit.",
        price: 120.00,
        comparePrice: 150.00,
        category: "outerwear",
        gender: "men",
        images: [
          "https://images.unsplash.com/photo-1505022610485-0249ba5b3675?auto=format&fit=crop&q=80&w=800",
          "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=800",
        ],
        colors: ["#e5e7eb", "#3b82f6", "#111111"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 28,
        rating: 4.8,
        reviewCount: 64,
        featured: true,
        isNew: true,
        tags: ["windbreaker", "outdoor", "new"],
      },
      {
        name: "Strider Running Shorts",
        slug: "strider-running-shorts",
        description: "5-inch inseam with built-in liner. Lightweight mesh construction for maximum airflow. Hidden zip pocket for your essentials.",
        price: 55.00,
        category: "bottoms",
        gender: "men",
        images: [
          "https://images.unsplash.com/photo-1517070208541-6d8fec9b8178?auto=format&fit=crop&q=80&w=800",
          "https://images.unsplash.com/photo-1539533018257-31021ab98ec7?auto=format&fit=crop&q=80&w=800",
        ],
        colors: ["#111111", "#374151"],
        sizes: ["XS", "S", "M", "L", "XL"],
        stock: 60,
        rating: 4.6,
        reviewCount: 82,
        featured: false,
        isNew: false,
        tags: ["running", "shorts", "training"],
      },
      {
        name: "Elevate Training Hoodie",
        slug: "elevate-training-hoodie",
        description: "Premium heavyweight fleece with kangaroo pocket and adjustable drawcord. Relaxed fit for freedom of movement during any activity.",
        price: 95.00,
        category: "tops",
        gender: "unisex",
        images: [
          "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800",
          "https://images.unsplash.com/photo-1578932750294-f5075e85f44a?auto=format&fit=crop&q=80&w=800",
        ],
        colors: ["#9ca3af", "#111111", "#374151"],
        sizes: ["XS", "S", "M", "L", "XL", "XXL"],
        stock: 36,
        rating: 4.9,
        reviewCount: 214,
        featured: true,
        isNew: false,
        tags: ["hoodie", "fleece", "bestseller"],
      },
      {
        name: "Core Compression Tights",
        slug: "core-compression-tights",
        description: "High-waisted compression tights with flattering paneling. 4-way stretch and quick-dry technology. Squat-proof fabric you can rely on.",
        price: 75.00,
        category: "bottoms",
        gender: "women",
        images: [
          "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&q=80&w=800",
          "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&q=80&w=800",
        ],
        colors: ["#111111", "#1f2937"],
        sizes: ["XS", "S", "M", "L", "XL"],
        stock: 54,
        rating: 4.8,
        reviewCount: 176,
        featured: true,
        isNew: false,
        tags: ["compression", "yoga", "training"],
      },
      {
        name: "Sprint Elite Bra",
        slug: "sprint-elite-bra",
        description: "Medium-impact sports bra with removable cups. Adjustable straps and hook-and-eye closure. Moisture-wicking fabric keeps you dry.",
        price: 48.00,
        category: "tops",
        gender: "women",
        images: [
          "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&q=80&w=800",
          "https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&q=80&w=800",
        ],
        colors: ["#111111", "#ec4899", "#6366f1"],
        sizes: ["XS", "S", "M", "L", "XL"],
        stock: 48,
        rating: 4.6,
        reviewCount: 92,
        featured: false,
        isNew: true,
        tags: ["sports bra", "women", "new"],
      },
      {
        name: "Trail Blazer Jacket",
        slug: "trail-blazer-jacket",
        description: "Insulated midlayer with DWR coating. 3 zip pockets, articulated patterning, and lightweight fill for warmth without bulk.",
        price: 165.00,
        comparePrice: 195.00,
        category: "outerwear",
        gender: "unisex",
        images: [
          "https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?auto=format&fit=crop&q=80&w=800",
          "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&q=80&w=800",
        ],
        colors: ["#111111", "#047857", "#1e40af"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 20,
        rating: 4.9,
        reviewCount: 57,
        featured: false,
        isNew: true,
        tags: ["jacket", "outdoor", "insulated", "new"],
      },
      {
        name: "Flex Flow Yoga Pants",
        slug: "flex-flow-yoga-pants",
        description: "Wide-leg silhouette with ultra-soft brushed fabric inside. High-rise waistband with no-roll grip. Perfect from studio to street.",
        price: 68.00,
        category: "bottoms",
        gender: "women",
        images: [
          "https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&q=80&w=800",
          "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&q=80&w=800",
        ],
        colors: ["#111111", "#6b7280", "#c084fc"],
        sizes: ["XS", "S", "M", "L", "XL"],
        stock: 39,
        rating: 4.7,
        reviewCount: 103,
        featured: false,
        isNew: false,
        tags: ["yoga", "women", "studio"],
      },
      {
        name: "Peak Performance Cap",
        slug: "peak-performance-cap",
        description: "6-panel structured cap with moisture-wicking sweatband. Adjustable snapback closure. Embroidered logo. One size fits most.",
        price: 32.00,
        category: "accessories",
        gender: "unisex",
        images: [
          "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&q=80&w=800",
          "https://images.unsplash.com/photo-1534215754734-18e55d13e346?auto=format&fit=crop&q=80&w=800",
        ],
        colors: ["#111111", "#ffffff", "#374151"],
        sizes: ["ONE SIZE"],
        stock: 100,
        rating: 4.5,
        reviewCount: 44,
        featured: false,
        isNew: false,
        tags: ["cap", "accessories", "unisex"],
      },
      {
        name: "Endure Long Sleeve",
        slug: "endure-long-sleeve",
        description: "Flatlock seams and thumbholes for cold-weather workouts. UV protection UPF 30+. Slim athletic fit with stretch mesh panels.",
        price: 58.00,
        category: "tops",
        gender: "men",
        images: [
          "https://images.unsplash.com/photo-1603252109612-24fa03d145c8?auto=format&fit=crop&q=80&w=800",
          "https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&q=80&w=800",
        ],
        colors: ["#111111", "#1e40af", "#374151"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        stock: 33,
        rating: 4.6,
        reviewCount: 71,
        featured: false,
        isNew: true,
        tags: ["long sleeve", "cold weather", "new"],
      },
      {
        name: "Pinnacle Sports Bag",
        slug: "pinnacle-sports-bag",
        description: "35L duffel with separate wet/dry compartment, trolley sleeve, and padded shoulder strap. Water-resistant ripstop exterior.",
        price: 79.00,
        comparePrice: 95.00,
        category: "accessories",
        gender: "unisex",
        images: [
          "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800",
          "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&q=80&w=800",
        ],
        colors: ["#111111", "#374151"],
        sizes: ["ONE SIZE"],
        stock: 25,
        rating: 4.8,
        reviewCount: 89,
        featured: true,
        isNew: false,
        tags: ["bag", "accessories", "gym"],
      },
    ];

    for (const product of products) {
      await ctx.db.insert("ec_products", product);
    }

    return { seeded: products.length };
  },
});
